name: Node.js CI/CD

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.18.2]


    steps:
      - name: Deploying to Contabo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

          script:
            cd /discord/MementoBot
            git pull
            npm install
            npm run build
